services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marquez
    ports:
      - "5432:5432"

  marquez:
    image: marquezproject/marquez:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marquez
    ports:
      - "3001:5000"
      - "3002:5001"
    depends_on:
      - postgres

  marquez-web:
    image: marquezproject/marquez-web:latest
    environment:
      MARQUEZ_HOST: marquez
      MARQUEZ_PORT: 5000
      WEB_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - marquez