apiVersion: v1
kind: Service

metadata:
  name: youtube-comment-analyzer-service

spec:
  selector:
    app: youtube-comment-analyzer

  ports:
    - port: 8000
      targetPort: 8000

  type: NodePort